ifdef::env-github[]
// General Settings
:status:
:outfilesuffix: .adoc

// Links & Images
// (must define images dir to use inline)
// :imagesdir: https://gist.githubusercontent.com/path/to/gist/revision/dir/with/all/images

// Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Flask Mega-Tutorial

This repo will be used to follow the Flask Mega-Tutorial, along with any additions or experimentation along the way:

https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world

== To Do

=== Tasks & Research

This will carry a list of tasks and questions for research, that are outside the scope of what the tutorial covers.

* What is `__init__.py`?
* Clarify about `__name__` when imported from another module.
* IDE? PyCharm Community is nice, but how does VSCode stack up?
Also investigate PyCharm Professional, which has Flask support built-in.
* Python virtual environments:
** Learn more about Python virtual environments.
** Provide a summary / write-up on Python virtual environments.
* Flask
** Learn more about Flask.
** Provide a summary / write-up on Flask.
* Is it worthwhile to keep a chapter by chapter summary in the README?
(will do so at the start; determine later if there's value, delete if not)


=== Course Outline

In addition to the above, the following is the status of my progress on this tutorial:

* Chapter 1: Hello, World! *- in progress*
* Chapter 2: Templates
* Chapter 3: Web Forms
* Chapter 4: Database
* Chapter 5: User Logins
* Chapter 6: Profile Page and Avatars
* Chapter 7: Error Handling
* Chapter 8: Followers
* Chapter 9: Pagination
* Chapter 10: Email Support
* Chapter 11: Facelift
* Chapter 12: Dates and Times
* Chapter 13: I18n and L10n
* Chapter 14: Ajax
* Chapter 15: A Better Application Structure
* Chapter 16: Full-Text Search
* Chapter 17: Deployment on Linux
* Chapter 18: Deployment on Heroku
* Chapter 19: Deployment on Docker Containers
* Chapter 20: Some JavaScript Magic
* Chapter 21: User Notifications
* Chapter 22: Background Jobs
* Chapter 23: Application Programming Interfaces (APIs) 



== Getting Started

The following are required for this tutorial:

- Python 3
- A Python 3 virtual environment
- Flask


=== Python 3

In new enough versions of Fedora, Python 3 is the default: `dnf install python`.
Additional Python packages should be installed via `pip`.

A Python interpreter, useful for testing out quick commands, can be opened using the `python` command from the CLI.
Use `exit()` when finished.

.Python Interpreter
[source, python]
----
$ python
Python 3.9.2 (default, Feb 20 2021, 00:00:00) 
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 1+1
2
>>> exit()
----



=== Python 3 Virtual Environment

Run the following command from the top-level of the project:

`python -m venv venv`

Once the virual environment is created, activate it:

`source venv/bin/activate`



=== Flask

To install Flask: `pip install Flask`

NOTE: Ensure that a virtual environment has been created and activated before running this step.

Once Flask is installed, verify it using the Python interpreter:

.Verify the Flask installation
[source, python]
----
>>> import flask
>>>
----


If Flask failed to install correctly, an error will occur on attempting to import:

.Flask installation failure: error message
[source, python]
----
>>> import flask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'flask'
>>>
----


== Chapter 1: Hello, World!

=== \\__init__.py

The file `app/\\__init__.py` was given the following content:

.\\__init__.py
[source, python]
----
from flask import Flask

app = Flask(__name__)

from app import routes
----

Each of these lines is worth breaking down for individual consideration:

[source, python]
----
from flask import Flask
----

This imports `Flask` (from the package `flask`), allowing an instance of the `Flask` class to be created.
This will be done on the next line of code.


[source, python]
----
app = Flask(__name__)
----

The `\\__name__` variable is a Python built-in variable which evaluates to the name of the current module.

* If run from the command line, the module name is `\\__main__` (i.e., `\\__name__ == "\\__main__"`)
* If imported from another module, use that module's name

The code above creates an object (`app`) which is an instance of the class `Flask`;
`app` is then used to import `routes`, which does not yet exist
(this will be defined later, but we know it's coming; to be discussed in further depth below).

TIP: Passing in `\\__name__` when creating the `Flask` object will almost always create what we are looking for;
advanced cases will be outside the scope of the tutorial.


[source, python]
----
from app import routes
----

The `routes` module is purposely imported at the end, instead of at the beginning as would normally be expected.
This is a workaround for *circular imports*, which are apparently a common occurrence in Flask.

Note that `app` here is different from the `app` on the line above.
Here, we are referring to the `app` package, which is the folder where `\\__init__.py` lives.
On the previous line, `app` is the variable holding the `Flask` class instance.
These names are unrelated, and either/or can be changed to something else
(though changing the package requires renaming the folder as well)

=== Routes

Routes refer to the endpoints exposed by the Flask application.

.routes.py
[source, python]
----
from app import app

@app.route('/')
@app.route('/index')
def index():
    return "Hello, World!"
----

The first line imports the object `app` from the `app` package;
i.e., bring in the `Flask` instance instantiated in `__init__.py`.
This is why the `from app import routes` line is at the end of `__init__.py` instead of at the top;
attempting to import `routes` before defining `app`, creates a circular reference, as shown by the error below:

[source, bash]
----
Error: While importing 'microblog', an ImportError was raised:

Traceback (most recent call last):
  File "FlaskTutorial/venv/lib64/python3.9/site-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "FlaskTutorial/microblog.py", line 1, in <module>
    from app import app
  File "FlaskTutorial/app/__init__.py", line 4, in <module>
    from app import routes
  File "FlaskTutorial/app/routes.py", line 1, in <module>
    from app import app
ImportError: cannot import name 'app' from partially initialized module 'app' (most likely due to a circular import) (FlaskTutorial/app/__init__.py)
----

IMPORTANT: The Flask app had to be run in order to get this error; steps to run are defined in the next section.


=== Flask App

Up through this point, two things have been created:

* The `app` package has been created with an endpoint (route)
* The package initialization logic to create a `Flask` instance and reference those endpoints.

The final piece of the puzzle is the ability to activate the `app` package:

.microblog.py
[source, python]
----
from app import app
----

TIP: `microblog.py` is used due to the nature of the tutorial, but the filename is not important -- only the content.


With this top-level script defined, the flask app is ready to run.
Set the `FLASK_APP` variable to the top-level script name (`microblog.py`, in this case) and then run the Flask application:


[source, bash]
----
$ export FLASK_APP=microblog.py
$ flask run
 * Serving Flask app 'microblog.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
----

TIP: The variable must be exported for each new shell, OR, it can be handled once via the `python-dotenv` package (to be discussed in another section below).


Verify that the application is running using any means for testing a RESTful `GET` endpoint (e.g., by hitting it through the browser, or via `curl`):

[source, bash]
----
$ curl http://localhost:5000
Hello, World!
----
